package carsharing;

class Query {
    final static String CREATE_COMPANY_TABLE = "CREATE TABLE IF NOT EXISTS COMPANY(" +
            "ID INTEGER AUTO_INCREMENT PRIMARY KEY, " +
            "NAME VARCHAR(255) NOT NULL UNIQUE);";
    final static String CREATE_CAR_TABLE = "CREATE TABLE IF NOT EXISTS CAR(" +
            "ID INTEGER AUTO_INCREMENT PRIMARY KEY, " +
            "NAME VARCHAR(255) NOT NULL UNIQUE, " +
            "COMPANY_ID INTEGER NOT NULL, " +
            "IS_AVAILABLE BOOLEAN, " +
            "FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID));";
    final static String CREATE_CUSTOMER_TABLE = "CREATE TABLE IF NOT EXISTS CUSTOMER(" +
            "ID INTEGER AUTO_INCREMENT PRIMARY KEY, " +
            "NAME VARCHAR(255) NOT NULL UNIQUE, " +
            "RENTED_CAR_ID INTEGER, " +
            "FOREIGN KEY (RENTED_CAR_ID) REFERENCES CAR(ID));";
    final static String SELECT_ALL = "SELECT * FROM %s;";
    final static String SELECT_ALL_COMPANY_CARS = "SELECT * FROM CAR WHERE COMPANY_ID=%d;";
    final static String SELECT_ALL_AVAILABLE_CARS = "SELECT * FROM CAR WHERE COMPANY_ID=%d" +
            "AND IS_AVAILABLE=TRUE;";
    final static String SELECT_CAR_BY_ID = "SELECT * FROM CAR WHERE ID=%d;";
    final static String SELECT_COMPANY_BY_ID = "SELECT * FROM COMPANY WHERE ID=%d;";
    final static String INSERT_COMPANY = "INSERT INTO COMPANY (NAME) VALUES ('%s');";
    final static String INSERT_CAR = "INSERT INTO CAR (NAME, COMPANY_ID, IS_AVAILABLE) VALUES ('%s', %d, TRUE);";
    final static String INSERT_CUSTOMER = "INSERT INTO CUSTOMER (NAME, RENTED_CAR_ID) VALUES ('%s', NULL);";
    final static String UPDATE_CUSTOMER_RENT = "UPDATE CUSTOMER SET RENTED_CAR_ID=%d WHERE ID=%d;";
    final static String UPDATE_CUSTOMER_RETURN = "UPDATE CUSTOMER SET RENTED_CAR_ID=NULL WHERE ID=%d;";
    final static String UPDATE_CAR_RENT = "UPDATE CAR SET IS_AVAILABLE = FALSE WHERE ID=%d;";
    final static String UPDATE_CAR_RETURN = "UPDATE CAR SET IS_AVAILABLE = TRUE WHERE ID=%d;";
}

